// Generated by wxt
export {}
declare global {
  const CAPTURE_DELAY: typeof import('/root/projects/snappage/utils/constants').CAPTURE_DELAY
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const FILENAME_MAX_LENGTH: typeof import('/root/projects/snappage/utils/constants').FILENAME_MAX_LENGTH
  const FILENAME_SANITIZE_REGEX: typeof import('/root/projects/snappage/utils/constants').FILENAME_SANITIZE_REGEX
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MAX_CAPTURE_TILES: typeof import('/root/projects/snappage/utils/constants').MAX_CAPTURE_TILES
  const MAX_PAGE_HEIGHT: typeof import('/root/projects/snappage/utils/constants').MAX_PAGE_HEIGHT
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const SCROLL_SETTLE_DELAY: typeof import('/root/projects/snappage/utils/constants').SCROLL_SETTLE_DELAY
  const browser: typeof import('wxt/browser').browser
  const buildFilename: typeof import('/root/projects/snappage/utils/sanitize').buildFilename
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const sanitizeFilename: typeof import('/root/projects/snappage/utils/sanitize').sanitizeFilename
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { CaptureMode, ImageFormat, OutputFormat, StartCaptureMessage, CaptureProgressMessage, CaptureCompleteMessage, CaptureErrorMessage, StitchImagesMessage, StitchResultMessage, StitchErrorMessage, PopupToBackground, BackgroundToPopup, BackgroundToOffscreen, OffscreenToBackground, Message } from '/root/projects/snappage/utils/messages'
  import('/root/projects/snappage/utils/messages')
}
